### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by Punit-Choudhary** [Pragmatic-Programmers/Under-Development-Page#6]
There is a link the text: `Designed with ❤ by Pragmatic Programmer` in website.
Clicking on link is not redirecting the linked website.

**Comment by ahmadfaizan965** [comment]
Typo corrected in href of the same. Now working properly.

**Comment by Punit-Choudhary** [comment]
@ahmadfaizan965 this was just to make @Darkneux familiar with GitHub.
Btw, thank you for the contribution.

**Comment by ahmadfaizan965** [comment]
Oops! Apologies...thanks 👍😊

**Comment by Punit-Choudhary** [comment]
@Darkneux solved the issue.
